export const ACTION_POST_TYPES = {
    GET_ALL: "GET_ALL",
    CREATE: "CREATE",
    IS_LOADING: "IS_LOADING",
    ERROR: "ERROR",
    RESET: "RESET",
}

export const ACTION_USER_TYPES = {
    REGISTER: "REGISTER",
    IS_LOADING: "IS_LOADING",
    ERROR: "ERROR",
    RESET: "RESET",
}