export const ACTION_POST_TYPES = {
    GET_ALL: "GET_ALL_POSTS",
    CREATE: "CREATE_POST",
    IS_LOADING: "IS_LOADING_POSTS",
    ERROR: "ERROR_POSTS",
    RESET: "RESET_POSTS",
}

export const ACTION_USER_TYPES = {
    REGISTER: "REGISTER_USER",
    LOGIN: "LOGIN_USER",
    IS_LOADING: "IS_LOADING_USER",
    IS_LOGGEDIN: "IS_LOGGEDIN_USER",
    ERROR: "ERROR_USER",
    RESET: "RESET_USER",
}